name: CI Stages Practice

on:
  push:
    branches: [ main ]

jobs:
  # Стадия сборки
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Application
        run: |
          echo "Compiling the code..."
          mkdir -p build/
          echo "Success" > build/app.bin

  # Стадия тестирования
  test:
    runs-on: ubuntu-latest
    needs: build # Ждем завершения сборки!
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          echo "Running tests..."
          exit 0 # 0 — успех, 1 — провал. Попробуй поменять на 1, чтобы увидеть ошибку.


