name: My First Pipeline

# ТЕСТ: Запуск при push в ветку main
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Используем чистую Ubuntu от GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Шаг 1: Копируем код из репозитория на сервер

      - name: Run Build
        run: echo "Building the project..." # Шаг 2: Имитация сборки

      - name: Run Tests
        run: |
          echo "Running unit tests..."
          echo "All tests passed!" # Шаг 3: Имитация тестов

